name: Tests
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'website/**'
      - 'data/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'website/**'
      - 'data/**'
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn install
      - run: yarn build:js
      - run: yarn test
